# Generated by Django 4.0 on 2022-10-12 16:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_region', models.CharField(default='', max_length=300, null=True)),
                ('employed', models.CharField(default='', max_length=300, null=True)),
                ('unemployed', models.CharField(default='', max_length=300, null=True)),
                ('children', models.CharField(default='', max_length=300, null=True)),
                ('adults', models.CharField(default='', max_length=300, null=True)),
                ('marriage_rate', models.CharField(default='', max_length=300, null=True)),
                ('birth_rate', models.CharField(default='', max_length=300, null=True)),
                ('death_rate', models.CharField(default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.CharField(default='', max_length=300, null=True)),
                ('cities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300, null=True), blank=True, size=None)),
                ('districts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300, null=True), blank=True, size=None)),
                ('population', models.CharField(default='', max_length=300, null=True)),
                ('demographics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_Structure.demographics')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_Structure.regions')),
            ],
        ),
    ]
