# Generated by Django 4.0 on 2022-10-11 12:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='cities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300, null=True), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='region',
            name='districts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300, null=True), blank=True, size=None),
        ),
    ]
