# Generated by Django 4.0 on 2022-10-12 03:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin_Structure', '0002_alter_region_cities_alter_region_districts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('const_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Structure.regions')),
            ],
        ),
        migrations.CreateModel(
            name='Electoral_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elec_area_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('elec_area_const', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gov_Structure.constituencies')),
            ],
        ),
        migrations.CreateModel(
            name='Gov_Ministries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_name', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Political_Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State_owned_enterprises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('directors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300, null=True), blank=True, size=None)),
                ('enterprise_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Structure.regions')),
            ],
        ),
        migrations.CreateModel(
            name='State_institutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('directors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300, null=True), blank=True, size=None)),
                ('enterprise_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Structure.regions')),
            ],
        ),
        migrations.CreateModel(
            name='Polling_Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('elctoral_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gov_Structure.electoral_area')),
                ('polling_const', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gov_Structure.constituencies')),
                ('polling_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Structure.regions')),
            ],
        ),
        migrations.CreateModel(
            name='Party_Executives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_executive', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('tenure', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('party_of_executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gov_Structure.political_parties')),
            ],
        ),
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('tenure', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('const_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gov_Structure.constituencies')),
                ('mp_party_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gov_Structure.political_parties')),
            ],
        ),
        migrations.CreateModel(
            name='Election_Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_election', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('pres_candidate', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('pres_candidate_results', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('parl_candidate', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('parl_candidate_results', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('name_of_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gov_Structure.political_parties')),
                ('results_polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gov_Structure.polling_stations')),
            ],
        ),
    ]
