# Generated by Django 4.1.3 on 2022-11-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gov_Structure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polling_stations',
            old_name='elctoral_area',
            new_name='electoral_area',
        ),
    ]
