# Generated by Django 4.1.3 on 2022-11-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin_Structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('region_located', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Structure.regions')),
            ],
        ),
    ]
