# Generated by Django 4.0 on 2022-10-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('network', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('IMEI', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
