# Generated by Django 4.0 on 2022-10-11 12:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(default='', max_length=300)),
                ('population', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=300)),
                ('population', models.PositiveIntegerField(null=True)),
                ('languages', models.CharField(blank=True, default='', max_length=300)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Bank.continents')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=300)),
                ('population', models.PositiveIntegerField(null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Bank.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Capitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300, null=True), blank=True, size=None)),
                ('capital', models.CharField(default='', max_length=300)),
                ('population', models.PositiveIntegerField(null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Bank.countries')),
            ],
        ),
    ]
